ANIME AREA
###
http://localhost:3000/anime
###
http://localhost:3000/anime/search/jujutsu
###
http://localhost:3000/anime/detail/jujutsu-kaisen-subtitle-indonesia/
###Ö
http://localhost:3000/anime/genre
###
http://localhost:3000/anime/genre/slice-of-life/
###
http://localhost:3000/anime/genre/slice-of-life/page/2
###
http://localhost:3000/anime/schedule
###
http://localhost:3000/anime/season
###
http://localhost:3000/anime/season/fall-2019
###
http://localhost:3000/anime/season/fall-2019/page/2
###
http://localhost:3000/anime/studio
###
http://localhost:3000/anime/studio/cloverworks/
###
http://localhost:3000/anime/studio/cloverworks/page/2
###
http://localhost:3000/anime/completed

###
MANGA AREA
###
http://localhost:3000/manga
###
http://localhost:3000/manga/page/1
###
http://localhost:3000/manga/detail/martial-peak
###
http://localhost:3000/manga/search/boku
###
http://localhost:3000/manga/genres
###
http://localhost:3000/manga/genre/action/1
###
http://localhost:3000/manga/popular/1
###
http://localhost:3000/manga/recommended
###
http://localhost:3000/manga/manhua/1
###
http://localhost:3000/manga/manhwa/1
###
http://localhost:3000/manga/chapter/martial-peak-chapter-1
###
